name: Deploy Server

on:
  push:
    branches:
      - master
    paths:
      - "src/*"
      - ".github/workflows/DeployServer.yml"
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: testing workflow
        run: echo "this workflow is working...yippee!!"
      - name: Add github username
        run: git config --global user.name 'anisha23554'
      - name: Add github email
        run: git config --global user.email 'dawaranisha52@gmail.com'
      - name: Add heroku remote
        run: git remote add heroku https://heroku:${{secrets.HEROKU_API_KEY}}@git.heroku.com/${{secrets.HEROKU_APP_NAME}}.git
      - name: Fetch repo
        run: git fetch --unshallow  
      - name: Push to heroku remote
        run: git push heroku master --force